.\" Process this file with                                                   
.\" groff -man -Tlatin1 epc.1                                                 
.\"                                                                          
.TH EPC 1 "2010 November 16" "epc version 1.0" "User Manual"
.SH NAME
epc \- Easy prompt changer
.SH SYNOPSIS                                                                 
.B epc
[flags]
command
.SH DESCRIPTION                                                                   
.B epc
Still writing the man page (sorry :-/ )
.SH BUGS                                                                        
.SH AUTHOR                                                                   
Juan Alberto Regalado Galván <00jarg@gmail.com>
.SH "SEE ALSO"                                                               
.BR bash (1)
